# 默认配置文件

# 数据配置
data:
  max_tcr_len: 30
  max_pep_len: 15
  max_hla_len: 34
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  n_clusters: 10
  clustering_method: "hierarchical"
  similarity_threshold: 0.7

# 模型配置
model:
  embedding_dim: 128
  hidden_dim: 256
  num_heads: 8
  num_layers: 4
  dropout: 0.1
  use_biochem_features: true

# 注意力机制配置
attention:
  physical_sliding:
    enabled: true
    sigma: 1.0
    num_iterations: 3
  data_driven:
    enabled: true
  fusion_method: "weighted_sum"  # weighted_sum, concat, or gated
  fusion_weights: [0.5, 0.5]  # 物理滑动和数据驱动的权重

# 训练配置
training:
  batch_size: 64
  lr: 1.0e-3
  weight_decay: 1.0e-5
  max_epochs: 200
  patience: 20
  loss_weights:
    tcr_pep: 1.0
    hla_pep: 1.0
    trimer: 1.0

# 优化器配置
optimizer:
  type: "adam"
  lr_scheduler:
    type: "reduce_on_plateau"
    factor: 0.5
    patience: 10
    min_lr: 1.0e-6

# 路径配置
paths:
  data_dir: "data"
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  model_dir: "models"
  log_dir: "logs"
  results_dir: "results" 